project_id = "ailynx-weather"

[functions.as1-weather-read]
enabled = true
verify_jwt = false
import_map = "./functions/as1-weather-read/deno.json"
entrypoint = "./functions/as1-weather-read/index.ts"

[functions.as1-validation-read]
enabled = true
verify_jwt = false
import_map = "./functions/as1-validation-read/deno.json"
entrypoint = "./functions/as1-validation-read/index.ts"

[functions.as1-horus-read]
enabled = true
verify_jwt = false
import_map = "./functions/as1-horus-read/deno.json"
entrypoint = "./functions/as1-horus-read/index.ts"

[functions.as1-asset-read]
enabled = true
verify_jwt = false
import_map = "./functions/as1-asset-read/deno.json"
entrypoint = "./functions/as1-asset-read/index.ts"

[functions.as1-admin-asset-read]
enabled = true
verify_jwt = false
import_map = "./functions/as1-admin-asset-read/deno.json"
entrypoint = "./functions/as1-admin-asset-read/index.ts"

[functions.pwa-visit-counter]
enabled = true
verify_jwt = false
import_map = "./functions/pwa-visit-counter/deno.json"
entrypoint = "./functions/pwa-visit-counter/index.ts"
