"use strict";

const dictionary = Object.freeze({
  en: Object.freeze({
    brandSubtitle: "Lynx Weather · timeframe observation", weather: "Weather", ai: "AI", community: "Community", manual: "Manual", joinFree: "Join free", free: "무료", selectAsset: "Select asset", available: "사용 가능", planned: "관측 준비", locked: "Locked", waiting: "관측 대기", calculating: "계산 중", noData: "데이터 없음", live: "Live", stale: "지연", invalid: "Invalid", publicData: "공개 데이터", liveObservation: "실시간 관측", tenMinuteRefresh: "10분 갱신", upgrade: "Upgrade",
    currentPrice: "Current price", observedClose: "Observed close", oneMinuteUpdate: "1 min update", waitingForData: "관측 대기", weatherDurability: "날씨 지속력", weatherChangeRate: "날씨 변화율", primaryTimeframe: "시장 리드 타임프레임", lynxWeather: "Lynx Weather", dailyTimeframes: "Daily timeframes", dailySubtitle: "Higher-timeframe weather board", timeframeMatrix: "Timeframe matrix", matrixSubtitle: "1H–24H · Lynx observation grid", marketDominance: "Market dominance", dominanceSubtitle: "공개 시장 데이터 · 무료", observedMarkets: "Observed markets", currentPlan: "Current plan: {plan}",
    validationStatus: "Validation status", validationSubtitle: "Closed-bar observation, not prediction", timeframe: "Timeframe", detailValidation: "Detail validation", viewInPro: "View in PRO", precisionValidation: "MAAT · MAAT2 precision validation", marketAdvisory: "Market advisory", noActiveAdvisory: "No active advisory", advisoryNote: "Verified market advisories will appear here when a supported LIVE contract is available.",
    login: "Log in", account: "Account", settings: "Settings", plan: "Plan", profilePreferenceDescription: "Language and main market are saved to your profile after sign-in.", setupRequired: "Setup required", signInRequired: "Log in to participate.", language: "Language", posts: "Posts", chat: "Live chat", compose: "Write post", send: "Send", noUploads: "Image, GIF, video, and file uploads are not supported.", referral: "Referral code", copy: "Copy link", providerGoogle: "Google", providerKakao: "Kakao", providerToss: "Toss", providerChatgpt: "ChatGPT", postPlaceholder: "Share a text update", chatPlaceholder: "Type a message",
    manualTitle: "Lynx Weather manual", manualIntro: "AiLynx shows verified market observations, not predictions.", manualOne: "Weather labels use the supported LIVE contract for each market and timeframe.", manualTwo: "Observation-pending, planned, locked, and no-data states are shown as-is; no value is invented.", manualThree: "MAAT and MAAT2 detail validation requires PRO.", close: "Close", totalVisitsWaiting: "Total visits · observation pending", totalVisits: "Total visits {total} · today {today}", lastObservation: "Last observation: {time} KST · {elapsed}", lastObservationUnavailable: "Last observation: time unavailable",
    cloudy: "Cloudy", sunny: "Sunny", partlyCloudy: "Partly cloudy", rainy: "Rainy", neutral: "계산 중", fullObservation: "{timeframe} full", publicContractWaiting: "Weather score is pending a public LIVE contract.", observedFreshness: "Observed close · {freshness}", liveData: "Live data", dataError: "Data error", offline: "Offline", offlineCache: "Offline cache", loading: "Loading", mainAsset: "Main market", savePreferences: "Save preferences", welcome: "Welcome to AiLynx", onboardingTitle: "Set your language and main market.", bitcoin: "Bitcoin", nasdaq: "Nasdaq",
  }),
  ko: Object.freeze({
    brandSubtitle: "Lynx Weather · 타임프레임 관측", weather: "날씨", ai: "AI", community: "커뮤니티", manual: "사용 안내", joinFree: "무료로 시작", free: "무료", selectAsset: "자산 선택", available: "사용 가능", planned: "관측 준비", locked: "잠김", waiting: "관측 대기", calculating: "계산 중", noData: "데이터 없음", live: "실시간", stale: "지연", invalid: "무효", publicData: "공개 데이터", liveObservation: "실시간 관측", tenMinuteRefresh: "10분 갱신", upgrade: "업그레이드",
    currentPrice: "현재가", observedClose: "관측 종가", oneMinuteUpdate: "1분 갱신", waitingForData: "관측 대기", weatherDurability: "날씨 지속력", weatherChangeRate: "날씨 변화율", primaryTimeframe: "시장 리드 타임프레임", lynxWeather: "Lynx Weather", dailyTimeframes: "일간 타임프레임", dailySubtitle: "상위 타임프레임 날씨판", timeframeMatrix: "타임프레임 매트릭스", matrixSubtitle: "1H–24H · Lynx 관측 그리드", marketDominance: "시장 점유율", dominanceSubtitle: "공개 시장 환경 · 무료", observedMarkets: "관측 자산", currentPlan: "현재 플랜: {plan}",
    validationStatus: "검증 상태", validationSubtitle: "예측이 아닌 확정 봉 관측", timeframe: "타임프레임", detailValidation: "상세 검증", viewInPro: "프로에서 확인", precisionValidation: "MAAT · MAAT2 정밀 검증", marketAdvisory: "시장 특보", noActiveAdvisory: "활성 특보 없음", advisoryNote: "지원되는 실시간 계약이 준비되면 검증된 시장 특보가 이곳에 표시됩니다.",
    login: "로그인", account: "계정", settings: "설정", plan: "플랜", profilePreferenceDescription: "로그인 후 언어와 주요 자산이 프로필에 저장됩니다.", setupRequired: "설정 필요", signInRequired: "로그인 후 이용할 수 있습니다.", language: "언어", posts: "게시글", chat: "실시간 채팅", compose: "글 작성", send: "보내기", noUploads: "이미지·GIF·동영상·파일 업로드는 지원하지 않습니다.", referral: "추천 코드", copy: "링크 복사", providerGoogle: "Google", providerKakao: "Kakao", providerToss: "Toss", providerChatgpt: "ChatGPT", postPlaceholder: "텍스트로 생각을 남겨보세요", chatPlaceholder: "메시지 입력",
    manualTitle: "Lynx Weather 안내", manualIntro: "AiLynx는 예측이 아닌 검증된 시장 관측을 보여줍니다.", manualOne: "날씨 라벨은 자산·타임프레임별로 지원되는 실시간 계약만 사용합니다.", manualTwo: "대기·예정·잠김·데이터 없음 상태는 있는 그대로 표시하며 값을 만들지 않습니다.", manualThree: "MAAT와 MAAT2 상세 검증은 PRO 전용입니다.", close: "닫기", totalVisitsWaiting: "총 방문 · 대기", totalVisits: "총 방문 {total} · 오늘 {today}", lastObservation: "마지막 관측: {time} KST · {elapsed}", lastObservationUnavailable: "마지막 관측: 시각 확인 불가",
    cloudy: "흐림", sunny: "맑음", partlyCloudy: "구름 조금", rainy: "비", neutral: "계산 중", fullObservation: "{timeframe} 전체 관측", publicContractWaiting: "공개 실시간 계약을 기다리는 중입니다.", observedFreshness: "관측 종가 · {freshness}", liveData: "실시간 데이터", dataError: "데이터 오류", offline: "오프라인", offlineCache: "오프라인 캐시", loading: "불러오는 중", mainAsset: "주요 자산", savePreferences: "설정 저장", welcome: "AiLynx에 오신 것을 환영합니다", onboardingTitle: "언어와 주요 자산을 선택하세요.", bitcoin: "비트코인", nasdaq: "나스닥",
  }),
});

const storageKey = "ailynx-language";
const preferred = () => "en";
let language = localStorage.getItem(storageKey) || preferred();
function t(key, values = {}) { const template = dictionary[language]?.[key] || dictionary.en[key] || key; return template.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`)); }
function applyTranslations() {
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAriaLabel)); });
  document.querySelectorAll("[data-language]").forEach((button) => button.classList.toggle("is-active", button.dataset.language === language));
  window.dispatchEvent(new CustomEvent("ailynx-language", {detail: {language}}));
}
function setLanguage(next) { if (!dictionary[next]) return; language = next; localStorage.setItem(storageKey, next); applyTranslations(); }
window.AiLynxI18n = Object.freeze({t, get language() { return language; }, setLanguage, applyTranslations});
