import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const read = (name) => readFile(new URL(name, root), "utf8");

test("membership runtime uses public Auth configuration with anonymous FREE fallback", async () => {
  const [config, runtime, authClient, client, i18n, gate, dashboard, admin, preview, adminPage, adminHtml, vercel, adminMigration] = await Promise.all([read("community-config.js"), read("public-runtime-config.js"), read("auth-client.js"), read("community-client.js"), read("i18n.js"), read("auth-gate.js"), read("lynx-dashboard-config.js"), read("admin-access.js"), read("admin-preview.js"), read("admin-page.js"), read("admin.html"), read("vercel.json"), read("supabase/migrations/20260909010000_create_server_verified_admin.sql")]);
  assert.match(config, /enabled: false/);
  assert.match(config, /authGateEnabled: true/);
  assert.match(runtime, /__AILYNX_SUPABASE_PUBLISHABLE_KEY__/);
  assert.match(authClient, /AUTH_UNAVAILABLE/);
  assert.match(authClient, /\/auth\/v1\/signup/);
  assert.match(authClient, /\/auth\/v1\/recover/);
  assert.match(config, /google: "DISABLED"/);
  assert.match(config, /chatgpt: "COMING_SOON"/);
  assert.match(config, /profilePersistenceAvailable: true/);
  assert.doesNotMatch(config, /adminUserIds|service_role/i);
  assert.match(client, /canUseCommunity/);
  assert.match(client, /beginOAuth/);
  assert.match(i18n, /localStorage/);
  assert.match(i18n, /ko:/);
  assert.match(i18n, /en:/);
  assert.match(i18n, /const preferred = \(\) => "en"/);
  assert.match(i18n, /weatherDurability/);
  assert.match(i18n, /marketAdvisory/);
  assert.match(gate, /requestAssetAccess/);
  assert.match(gate, /ailynx-auth-logout/);
  assert.match(gate, /canFetchLive/);
  assert.doesNotMatch(dashboard, /\bassets:/);
  assert.match(dashboard, /label: "플러스"/);
  assert.match(admin, /isAdminMembership/);
  assert.match(admin, /is_current_user_admin/);
  assert.doesNotMatch(admin, /adminUserIds|localStorage|sjjunsaxsmax@gmail\.com|service_role/i);
  assert.match(adminMigration, /create table if not exists public\.admin_users/i);
  assert.match(adminMigration, /references auth\.users\(id\) on delete cascade/i);
  assert.match(adminMigration, /alter table public\.admin_users enable row level security/i);
  assert.match(adminMigration, /returns boolean[\s\S]*is_current_user_admin\(\)/i);
  assert.match(adminMigration, /grant execute on function public\.is_current_user_admin\(\) to anon, authenticated/i);
  assert.match(preview, /isCurrentUserAdmin/);
  assert.match(preview, /ADMIN_PREVIEW_MODES/);
  assert.doesNotMatch(preview, /localStorage|service_role|subscriptions\.plan_code/i);
  assert.doesNotMatch(adminMigration, /sjjunsaxsmax@gmail\.com/i);
  assert.match(vercel, /"source": "\/admin"[\s\S]*"destination": "\/admin\.html"/);
  assert.match(adminPage, /if \(!verified \|\| !session\?\.user\) return redirectToWeather\(\)/);
  assert.match(adminPage, /shell\.replaceChildren/);
  assert.doesNotMatch(adminPage, /innerHTML|service_role/i);
  assert.match(adminPage, /권한 미리보기/);
  assert.match(adminPage, /실측 관측 상태/);
  assert.match(adminPage, /fetchAdminAssetObservations/);
  assert.match(adminHtml, /admin-preview\.js\?v=1/);
  assert.match(adminHtml, /id="adminPageShell" hidden/);
  assert.doesNotMatch(dashboard, /activePlan|PLUS/);
});

test("community migration enforces RLS, text-only content, and referral/Xp invariants", async () => {
  const sql = await read("supabase/migrations/20260908113000_create_member_community.sql");
  for (const table of ["profiles", "community_posts", "community_comments", "chat_messages", "community_xp_events"]) assert.match(sql, new RegExp(`alter table public\\.${table} enable row level security`, "i"));
  assert.match(sql, /SELF_REFERRAL_REJECTED/);
  assert.match(sql, /unique \(referrer_id, referred_user_id\)|referred_user_id uuid not null unique/i);
  assert.match(sql, /CHAT_RATE_LIMITED/);
  assert.match(sql, /COMMUNITY_URL_SPAM_REJECTED/);
  assert.match(sql, /unique \(user_id, event_type, source_kind, source_id\)/);
  assert.doesNotMatch(sql, /storage\.objects|create bucket|attachment/i);
});

test("community UI retains posts/chat and adds email Auth controls without upload", async () => {
  const [html, ui, advisory, gate] = await Promise.all([read("index.html"), read("member-community.js"), read("market-advisory-config.js"), read("auth-gate.js")]);
  assert.match(html, /data-community-tab="posts"/);
  assert.match(html, /data-community-tab="chat"/);
  assert.match(html, /emailLoginForm/);
  assert.match(html, /emailSignupForm/);
  assert.match(html, /passwordResetForm/);
  assert.doesNotMatch(html, /type="file"|<input[^>]+file/i);
  assert.match(ui, /emojiManifest/);
  assert.match(ui, /resetPasswordForEmail/);
  assert.match(ui, /navigator\.clipboard/);
  assert.match(html, /authGateDialog/);
  assert.match(html, /onboardingDialog/);
  assert.match(html, /JOIN FREE/);
  assert.match(html, /MARKET ADVISORY/);
  assert.match(html, /manualButton/);
  assert.match(html, /manualDialog/);
  assert.match(html, /id="planDialog"/);
  assert.match(html, /플러스에서 확인/);
  for (const label of ["회원 전용 기능", "무료 회원가입", "플러스 보기", "프리미엄 보기", "프로 보기", "구독 준비 중"]) assert.match(html, new RegExp(label));
  assert.doesNotMatch(html, /id="adminEntry"|id="adminDialog"/);
  assert.match(ui, /AiLynxAdminAccess/);
  assert.match(ui, /renderAdminShell/);
  assert.match(ui, /initializePlanDialog/);
  assert.match(ui, /data-open-plan/);
  assert.match(ui, /data-plan-interest/);
  assert.match(gate, /membershipUpgradeDescription/);
  assert.match(gate, /planButton\.dataset\.planTarget/);
  assert.match(advisory, /active: null/);
  assert.match(advisory, /evidencePlan: "PRO"/);
});
