import assert from "node:assert/strict";
import test from "node:test";
globalThis.window = globalThis;
await import("../weather-engine.js");

const valid = (payload) => ({available: true, quality: {valid: true}, payload});
function fullInput() {
  return {timeframe: "4H", horus: {available: true, quality: {valid: true}, state: {score: 40}}, maat: valid({aggregate: {score: 60}, sensors: Object.fromEntries(["a", "b", "c", "d", "e", "f"].map((key) => [key, {valid: true}])), stopwatch: {noise_score: 20}}), hub: valid({scores: {structure: 70, force: 50, window: 80}}), time: valid({time: {valid: true, score: 40, noise_score: 30}})};
}
test("FULL weather score is deterministic and bounded", () => { const result = globalThis.AiLynxWeatherEngine.computeWeatherScore(fullInput()); assert.equal(result.coverage, "FULL"); assert.ok(result.score >= 0 && result.score <= 100); });
test("invalid inputs do not manufacture a score", () => { const input = fullInput(); input.time.quality.valid = false; assert.equal(globalThis.AiLynxWeatherEngine.computeWeatherScore(input), null); });
test("history metrics wait instead of inventing values", () => { const engine = globalThis.AiLynxWeatherEngine; assert.equal(engine.computeDurability([]), null); assert.equal(engine.computeChangeRate([]), null); });
test("history metrics use only ordered valid snapshots from one timeframe", () => { const engine = globalThis.AiLynxWeatherEngine; const history = [{timeframe: "4H", score: 40, state: "CLOUDY", valid: true, noise: 30}, {timeframe: "4H", score: 52, state: "CLOUDY", valid: true, noise: 30}]; assert.equal(engine.computeChangeRate(history), 24); assert.equal(engine.computeDurability(history), 90); assert.equal(engine.computeChangeRate([{...history[0]}, {...history[1], timeframe: "8H"}]), null); });
test("weather classification honors every boundary", () => { const classify = globalThis.AiLynxWeatherEngine.classifyWeather; assert.equal(classify(0).state, "RAIN"); assert.equal(classify(25).state, "RAIN"); assert.equal(classify(26).state, "CLOUDY"); assert.equal(classify(51).state, "CLOUDY"); assert.equal(classify(52).state, "PARTLY_CLOUDY"); assert.equal(classify(75).state, "PARTLY_CLOUDY"); assert.equal(classify(76).state, "SUNNY"); assert.equal(classify(100).state, "SUNNY"); });

const snapshot = (overrides = {}) => ({assetId: "BTCUSD", timeframe: "4H", majorTimeframe: "4H", score: 50, state: "CLOUDY", valid: true, noise: 20, quality: "GOOD", freshness: "FRESH", ...overrides});
test("repeated score, weather, and major timeframe produce very strong persistence", () => { const engine = globalThis.AiLynxWeatherEngine; const history = [snapshot(), snapshot(), snapshot(), snapshot()]; assert.equal(engine.computeDurability(history), 100); assert.equal(engine.computeChangeRate(history), 0); assert.equal(engine.describePersistence(100), "VERY STRONG"); assert.equal(engine.describeChangeRate(0), "VERY CALM"); });
test("score shock and weather transition raise absolute change rate", () => { const engine = globalThis.AiLynxWeatherEngine; const calm = engine.computeChangeRate([snapshot(), snapshot({score: 54})]); const shock = engine.computeChangeRate([snapshot(), snapshot({score: 80, state: "SUNNY"})]); assert.ok(shock > calm); assert.ok(shock >= 60); });
test("major timeframe transition lowers persistence and raises change rate", () => { const engine = globalThis.AiLynxWeatherEngine; const stable = [snapshot(), snapshot({score: 52})]; const shifted = [snapshot(), snapshot({score: 52, majorTimeframe: "1D"})]; assert.ok(engine.computeDurability(shifted) < engine.computeDurability(stable)); assert.ok(engine.computeChangeRate(shifted) > engine.computeChangeRate(stable)); });
test("quality penalties reduce persistence without inventing invalid history", () => { const engine = globalThis.AiLynxWeatherEngine; const good = [snapshot(), snapshot({score: 52})]; const conflict = [snapshot(), snapshot({score: 52, quality: "CONFLICT"})]; assert.ok(engine.computeDurability(conflict) < engine.computeDurability(good)); });
test("missing prior, stale, invalid, and cross-asset histories wait", () => { const engine = globalThis.AiLynxWeatherEngine; assert.equal(engine.computeDurability([snapshot()]), null); assert.equal(engine.computeChangeRate([snapshot(), snapshot({freshness: "STALE"})]), null); assert.equal(engine.computeChangeRate([snapshot(), snapshot({valid: false})]), null); assert.equal(engine.computeChangeRate([snapshot(), snapshot({assetId: "XAUUSD"})]), null); });
test("persistence and change rate always stay within the 0 to 100 range", () => { const engine = globalThis.AiLynxWeatherEngine; const history = [snapshot({score: 0, state: "RAIN", quality: "CONFLICT", freshness: "AGING"}), snapshot({score: 100, state: "SUNNY", majorTimeframe: "1W", quality: "CONFLICT", freshness: "AGING"})]; for (const value of [engine.computeDurability(history), engine.computeChangeRate(history)]) assert.ok(value >= 0 && value <= 100); });
