begin;
create table if not exists public.as1_raw_events (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default now(),
  schema_version text not null,
  satellite_id text not null,
  platform text not null,
  layout_id text not null,
  observer text not null,
  code_version text not null,
  source_profile_code text not null,
  ticker_id text not null,
  venue text not null,
  symbol text not null,
  timeframe text not null,
  bar_open_time bigint not null,
  bar_close_time bigint not null,
  sent_at bigint not null,
  bar_duration_ms bigint not null,
  packet_type text not null,
  confirmed boolean not null,
  sensor_quality text not null,
  valid boolean not null,
  flags jsonb not null default '[]'::jsonb,
  client_event_key text not null,
  raw_envelope jsonb not null,
  constraint as1_raw_events_timing_check check (bar_close_time > bar_open_time),
  constraint as1_raw_events_duration_check check (bar_duration_ms = bar_close_time - bar_open_time),
  constraint as1_raw_events_flags_array_check check (jsonb_typeof(flags) = 'array'),
  constraint as1_raw_events_raw_object_check check (jsonb_typeof(raw_envelope) = 'object')
);
create unique index if not exists as1_raw_events_client_event_key_uidx
  on public.as1_raw_events (client_event_key);
create index if not exists as1_raw_events_received_at_idx
  on public.as1_raw_events (received_at desc);
create index if not exists as1_raw_events_observation_idx
  on public.as1_raw_events (ticker_id, timeframe, bar_close_time desc);
create index if not exists as1_raw_events_weather_read_idx
  on public.as1_raw_events (
    layout_id,
    ticker_id,
    timeframe,
    packet_type,
    sensor_quality,
    confirmed,
    valid,
    bar_close_time desc
  );
comment on table public.as1_raw_events is
  'AiLynx LIVE raw ledger. The 24-column contract mirrors the archived AS1 v1.3 source ledger.';
comment on column public.as1_raw_events.client_event_key is
  'Semantic event identity used for idempotent ingestion.';
comment on column public.as1_raw_events.raw_envelope is
  'Lossless original TradingView JSON envelope.';
create table if not exists public.as1_raw_events_archive (
  archive_id bigint generated by default as identity primary key,
  source_project_ref text not null,
  source_event_id bigint not null,
  archive_batch text not null,
  archived_at timestamptz not null default now(),
  received_at timestamptz not null,
  schema_version text not null,
  satellite_id text not null,
  platform text not null,
  layout_id text not null,
  observer text not null,
  code_version text not null,
  source_profile_code text not null,
  ticker_id text not null,
  venue text not null,
  symbol text not null,
  timeframe text not null,
  bar_open_time bigint not null,
  bar_close_time bigint not null,
  sent_at bigint not null,
  bar_duration_ms bigint not null,
  packet_type text not null,
  confirmed boolean not null,
  sensor_quality text not null,
  valid boolean not null,
  flags jsonb not null default '[]'::jsonb,
  client_event_key text not null,
  raw_envelope jsonb not null,
  constraint as1_raw_events_archive_timing_check check (bar_close_time > bar_open_time),
  constraint as1_raw_events_archive_duration_check check (bar_duration_ms = bar_close_time - bar_open_time),
  constraint as1_raw_events_archive_flags_array_check check (jsonb_typeof(flags) = 'array'),
  constraint as1_raw_events_archive_raw_object_check check (jsonb_typeof(raw_envelope) = 'object')
);
create unique index if not exists as1_raw_events_archive_source_id_uidx
  on public.as1_raw_events_archive (source_project_ref, source_event_id);
create unique index if not exists as1_raw_events_archive_event_key_uidx
  on public.as1_raw_events_archive (source_project_ref, client_event_key);
create index if not exists as1_raw_events_archive_received_at_idx
  on public.as1_raw_events_archive (received_at desc);
create index if not exists as1_raw_events_archive_observation_idx
  on public.as1_raw_events_archive (ticker_id, timeframe, bar_close_time desc);
comment on table public.as1_raw_events_archive is
  'Immutable historical-memory ledger. Rows retain source project, source id, archive batch, and the full AS1 raw contract.';
alter table public.as1_raw_events enable row level security;
alter table public.as1_raw_events_archive enable row level security;
revoke all on table public.as1_raw_events from anon, authenticated;
revoke all on table public.as1_raw_events_archive from anon, authenticated;
grant all on table public.as1_raw_events to service_role;
grant all on table public.as1_raw_events_archive to service_role;
grant usage, select on sequence public.as1_raw_events_id_seq to service_role;
grant usage, select on sequence public.as1_raw_events_archive_archive_id_seq to service_role;
commit;
