-- Dedicated immutable ledger for validated ailynx.history.v0.1 packets.
-- Deliberately separate from AS1 TradingView raw-event LIVE and ARCHIVE ledgers.

begin;
create table public.ailynx_history_packets (
  history_id bigint generated by default as identity primary key,
  history_schema_version text not null,
  record_type text not null,
  observed_at timestamptz not null,
  observed_at_kst_text text not null,
  timestamp_precision text,
  source_room jsonb not null,
  source_system jsonb not null,
  instrument jsonb not null,
  timeframe text not null,
  state jsonb not null,
  metrics jsonb not null,
  interpretation jsonb not null,
  next_check jsonb not null,
  quality jsonb not null,
  source_reference jsonb not null,
  archive jsonb not null,
  dedup_key text not null,
  raw_payload jsonb,
  packet_json jsonb not null,
  source_file text not null,
  source_line integer not null check (source_line > 0),
  content_sha256 text not null,
  import_batch text not null,
  created_at timestamptz not null default now(),
  constraint ailynx_history_packets_schema_check
    check (history_schema_version = 'ailynx.history.v0.1'),
  constraint ailynx_history_packets_metrics_array_check
    check (jsonb_typeof(metrics) = 'array'),
  constraint ailynx_history_packets_packet_object_check
    check (jsonb_typeof(packet_json) = 'object'),
  constraint ailynx_history_packets_archive_object_check
    check (jsonb_typeof(archive) = 'object'),
  constraint ailynx_history_packets_dedup_key_uidx unique (dedup_key)
);
create index ailynx_history_packets_observed_at_idx
  on public.ailynx_history_packets (observed_at desc);
create index ailynx_history_packets_record_type_idx
  on public.ailynx_history_packets (record_type, observed_at desc);
create index ailynx_history_packets_asset_tf_idx
  on public.ailynx_history_packets ((instrument ->> 'asset_key'), timeframe, observed_at desc);
create index ailynx_history_packets_room_idx
  on public.ailynx_history_packets ((source_room ->> 'room_name'));
create index ailynx_history_packets_quality_idx
  on public.ailynx_history_packets ((quality ->> 'status'));
comment on table public.ailynx_history_packets is
  'Immutable, lossless ailynx.history.v0.1 ledger. Not a TradingView raw-event table.';
comment on column public.ailynx_history_packets.packet_json is
  'Complete original validated packet retained for lossless history and schema evolution.';
alter table public.ailynx_history_packets enable row level security;
revoke all on table public.ailynx_history_packets from anon, authenticated;
grant all on table public.ailynx_history_packets to service_role;
grant usage, select on sequence public.ailynx_history_packets_history_id_seq to service_role;
commit;
